export type WalmartProduct = {
  wpId: number;
  Id: string;
  CatalogId: string;
  CampaignId: string;
  CampaignName: string;
  CatalogItemId: string;
  Name: string;
  Description: string;
  Manufacturer: string;
  Url: string;
  ImageUrl: string;
  Currency: string;
  StockAvailability: string;
  Gtin: string;
  Category: string;
  SubCategory: string;
  IsParent: string;
  Text2: string;
  Uri: string;
  CurrentPrice: string;
  OriginalPrice: string;
  DiscountPercentage: string;
};
